### ISSUE TITLE
Where is OptimistAtomicQueue?

### ISSUE THREAD

**Issue by pfeatherstone** [max0x7ba/atomic_queue#27] opened 2020-11-10 15:31 UTC
I cannot find OptimistAtomicQueue in any of the header files...

**Comment by pfeatherstone** [comment] 2020-11-10 15:40
Do you have to use ```atomic_queue::RetryDecorator``` ?

**Comment by max0x7ba** [comment] 2020-11-10 16:09
Duplicate of #25

**Closed by max0x7ba** 2020-11-10 16:09 UTC
